version: '3'

services:
  redis:
    image: "redis:alpine"
  nprobe:
    image: "andreytp/nprobe:latest"
    command: ['nprobe', '--interface', 'en4', '--collector', 'none', '--collector-port', '2055', '--zmq', 'tcp://*:1234']
    ports:
     - "2055:2055/udp"
  ntopng:
    image: "andreytp/ntopng:latest"
    command: ["ntopng", "--redis", "redis", "--interface", "tcp://nprobe:1234", "--local-networks", "192.168.3.0/24", "--disable-login", "1"]
    ports:
     - "3000:3000"
    depends_on:
     - nprobe
     - redis
